services:
  db:
    image: postgres:17.6
    container_name: doc_viewer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doc_viewer_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres "]
      interval: 5s
      timeout: 5s
      retries: 10

  doc_viewer_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc_viewer_backend
    depends_on:
      - db
    command: poetry run uvicorn app.doc_viewer_back.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432

volumes:
  db_data:
